CREATE TABLE categories (
  ID int IDENTITY(1,1) PRIMARY KEY,
  NAME varchar(50) NOT NULL,
  DESCRIPTION text NOT NULL,
  TAGS varchar(500) NOT NULL
)

CREATE TABLE notifications (
  EMAIL_ID varchar(50) NOT NULL,
  ID int IDENTITY(1,1) PRIMARY KEY,
  TITLE varchar(50) NOT NULL,
  DETAIL text NOT NULL
)

CREATE TABLE order_data (
  ID int IDENTITY(1,1) PRIMARY KEY,
  EMAIL_ID varchar(50) NOT NULL,
  PAYMENT_STATUS int NOT NULL,
  DATE_TIME datetime default CURRENT_TIMESTAMP,
  ITEM_LIST varchar(200) NOT NULL,
  TOTAL_AMOUNT FLOAT NOT NULL
)

CREATE TABLE project (
  ID int IDENTITY(1,1) PRIMARY KEY,
  NAME varchar(50) NOT NULL,
  DESCRIPTION text NOT NULL,
  MEDIA varbinary(5000) NOT NULL,
  PRICE FLOAT NOT NULL,
  DATA varbinary(5000) NOT NULL,
  UPLOADER varchar(50) NOT NULL,
  UPLOADED_TIME datetime default CURRENT_TIMESTAMP,
  CATEGORIES varchar(50) NOT NULL,
  IS_VERIFIED tinyint NOT NULL
)


CREATE TABLE users (
  EMAIL_ID varchar(50) NOT NULL,
  PASSWORD varchar(20) NOT NULL,
  TYPE varchar(20) NOT NULL
)


CREATE TABLE user_details (
  EMAIL_ID varchar(50) NOT NULL,
  FIRST_NAME varchar(50) NOT NULL,
  LAST_NAME varchar(50) NOT NULL,
  PHONE_NO varchar(13) NOT NULL,
  DOB date NOT NULL,
  WISHLIST varchar(500) NOT NULL,
  CART_ITEM varchar(500) NOT NULL,
  MY_PROJECTS varchar(500) NOT NULL,
  PURCHASING varchar(500) NOT NULL
)

ALTER TABLE users
  ADD PRIMARY KEY (EMAIL_ID);

ALTER TABLE user_details
  ADD PRIMARY KEY (EMAIL_ID);

ALTER TABLE notifications
  ADD CONSTRAINT notifications_ibfk_1 FOREIGN KEY (EMAIL_ID) REFERENCES users (EMAIL_ID);

ALTER TABLE user_details
  ADD CONSTRAINT user_details_ibfk_1 FOREIGN KEY (EMAIL_ID) REFERENCES users (EMAIL_ID);

ALTER TABLE users ADD CONSTRAINT
user_type_constraint CHECK (TYPE = 'user' OR TYPE = 'admin');

ALTER TABLE users ADD CONSTRAINT df_user_type DEFAULT 'user' FOR TYPE;

ALTER TABLE project ADD CONSTRAINT DF_project DEFAULT GETDATE() FOR UPLOADED_TIME

ALTER TABLE order_data ADD CONSTRAINT DF_order_data DEFAULT GETDATE() FOR DATE_TIME