- name: JMeter Test
  uses: QAInsights/PerfAction@v3.1
  with:
    test-plan-path: ./jmeter.jmx
    args: ""
- name: Upload Results
  uses: actions/upload-artifact@v2
  with:
    name: jmeter-results
    path: result.jtl