on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
          args: ""
      - name: Create Folder
        uses: actions/checkout@v3
        with:
          run: mkdir -p path/to/artifact
      - name: Create File
        uses: actions/checkout@v3
        with:
          run: echo hello > path/to/artifact/result.jtl
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/result.jtl