on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    steps:
      - name: JMeter Test
        uses: QAInsights/PerfAction@v3.1
        with:
          test-plan-path: ./jmeter.jmx
          args: ""
          artifacts:
            paths:
              - testresults.jtl
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/result.jtl